---
- name: install-required-roles--openshift-applier--with-ansible-galaxy
  hosts: localhost
  tasks:
    - name: install-ansible-roles
      local_action: command ansible-galaxy install -r requirements.yml -p roles/

- name: Deploy {{ target }} 
  hosts: "{{ target }}"
  vars:
    nodejs_namespace: "{{ project_name }}"
    project_params_dict:
        NAMESPACE: "{{ project_name }}"
        NAMESPACE_DISPLAY_NAME: "{{ project_name }}"
        NAMESPACE_DESCRIPTION: "{{ project_name }}"  
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
