---
apiVersion: v1
kind: Template
labels:
  template: projectrequest-template
message: |-
  The following project/namespace has been created: ${NAMESPACE}
metadata:
  annotations:
    description: |-
      ProjectRequest Template
  creationTimestamp: null
  name: ${NAMESPACE}
objects:
- apiVersion: v1
  kind: ProjectRequest
  metadata:
    name: ${NAMESPACE}
  description: '${NAMESPACE_DESCRIPTION}' 
  displayName: '${NAMESPACE_DISPLAY_NAME}'
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: deny-by-default
    namespace: ${NAMESPACE}
  spec:
    podSelector:
    ingress: []
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-from-same-namespace
    namespace: ${NAMESPACE}
  spec:
    podSelector:
    ingress:
    - from:
      - podSelector: {}
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-from-default-namespace
    namespace: ${NAMESPACE}
  spec:
    podSelector:
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: ${NAMESPACE}
parameters:
- description: Name
  displayName: Name
  name: NAMESPACE
  required: true
- description: DisplayName
  displayName: DisplayName
  name: NAMESPACE_DISPLAY_NAME
  required: true
- description: Description
  displayName: Description
  name: NAMESPACE_DESCRIPTION
